# Generated by Django 5.2.8 on 2025-11-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=180)),
                ('location', models.CharField(verbose_name=189)),
                ('company', models.CharField(verbose_name=90)),
                ('salary', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
